# Maintainer: hijiri

export GREP_COLOR='1;37;41'

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/Users/hijiri/.vim/latex:$PATH 
export PATH=$PATH:/Users/hijiri/.nodebrew/current/bin

export desk=/Users/hijiri/Documents/workspace/ 
export work=/Users/hijiri/Public/OneDrive
export share_juno=/Users/hijiri/Public/Juno/
export share_duho=/Users/hijiri/Public/Duho/

export home=/Users/hijiri/
export root=/private/var/root/

export NVM_DIR=~/.nvm
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
export apacheconfig=/usr/local/etc/apache2/2.4/extra/

# OpenSSH
export SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
