# Maintainer: hijiri

alias od='od -txlz -Ax -v'
alias grep='grep -E --color=auto'

alias cp='cp -iv'
alias rm='rm -iv'
alias mv='mv -iv'

alias ls='ls -G'
alias ll='ls -l'
alias la='ls -a'
alias lx='ll -a'

alias _cleanup='sudo purge'
alias python='python3'
alias htop='sudo htop'


bindkey -e

autoload -U compinit promptinit

setopt auto_cd

alias ...='cd ../../'
alias ....='cd ../../../'

setopt auto_pushd
setopt pushd_ignore_dups
#setopt extended_glob
setopt hist_ignore_all_dups


# Complement setting
autoload -U compinit promptinit
compinit
zstyle ':completion:*:default' menu select=1
zstyle ':completion::complete:*' use-cache true

autoload colors
zstyle ':completion:*' list-colors "${LS_COLORS}"

zstyle ':completion:*:sudo:*' command-path \
   /usr/local/sbin /usr/local/bin \
   /usr/sbin /usr/bin /sbin /bin  \

autoload zed
autoload -U zcalc

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end
bindkey "^R" history-incremental-pattern-search-backward
bindkey "^S" history-incremental-pattern-search-forward

LISTMAX=1000
WORDCHARS="$WORDCHARS|:"

# This config link online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help


fpath=(/usr/local/share/zsh-completions $fpath)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# My Zshell design
autoload colors
colors
PROMPT="%{${fg[blue]}%}%m: %n%(!.#.%% )%{${reset_color}%}"
PROMPT2="%{${fg[blue]}%}%_> %{${reset_color}%}"
SPROMPT="%{${fg[green]}%}correct: %R -> %r [nyae]? %{${reset_color}%}"
RPROMPT="%{${fg[blue]}%}[%./]%{${reset_color}%}"

# Recompile
if [ ~/.zshrc -nt ~/.zshrc.zwc ]; then
   zcompile ~/.zshrc
fi

# setting for size of history
HISTFILE=$HOME/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
PATH=${PATH}:~/bin

HISTTIMEFORMAT="[%M/%D/%Y %H:%M:%S]"

# Move key bind
zmodload zsh/complist
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history

