" License: MIT
" Maintainer: alicengh

filetype off
filetype plugin indent off

set runtimepath+=~/.vim/,~/.vim/after

runtime! indent/*.vim
runtime! custom/stdvim/*.vim

" if isdirectory(expand('~/.vim/bundle/neobundle.vim'))
"   runtime! custom/neobundle/*.vim
" endif

filetype indent on
filetype plugin indent on

""" END: VIMRC """
