" Maintainer:   alicengh

set runtimepath+=~/.vim/

runtime! indent/*.vim
runtime! custom/basic/*.vim

if isdirectory(expand('~/.vim/bundle/neobundle.vim'))
  runtime! custom/neobundle/*.vim
endif

""" END VIMRC """
